name: CI

on: [push]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: [11, 17, 21]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup clojure-lsp
        uses: clojure-lsp/setup-clojure-lsp@v1
        with:
          clojure-lsp-version: 2025.08.25-14.21.46

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.2.1565
          bb: 1.12.208

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: clojure-lsp
        run: clojure-lsp diagnostics

      - name: splint
        run: clojure -M:provided:dev:test:splint

      - name: tests
        run: |
          clojure -T:build compile-java
          bb lazytest --output summary
          clojure -M:v1.10:provided:dev:test:ci --output summary
          clojure -M:v1.11:provided:dev:test:ci --output summary
          clojure -M:v1.12:provided:dev:test:ci --output summary
